config/routes.rb
Encatec::Application.routes.draw do
  root to: 'home#index'

  match '/contact' => 'home#create_contact', via: 'post'
  match '/inscricao' => 'inscreva_se#index', as: 'inscreva_se'

end

app/models/contact.rb
class Contact
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => 'Nome'}
  validates :email, :presence => {:message =>  'Email'}
  validates :email, :format => {:with => %r{.+@.+\..+}, :message =>  'Email invalido', :allow_blank => true}
  validates :message, :presence => {:message =>  'Mensagem'}

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  validates :title, :presence => true
  validates :content, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  before_save :encrypt_password
  after_save :clear_password

  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..60 }
  validates :password, :presence => true
  #Only on Create so other actions like update password attribute can be nil
  validates_length_of :password, :in => 6..16, :message=>"A senha deve ter entre 6 a 16 caracteres."

  attr_accessible :username, :password, :password_confirmation

  def self.authenticate(username="", password="")
    user = User.find_by_username(username)

    if user && user.match_password(password)
      return user
    else
      return false
    end
  end

  def match_password(password="")
    encrypted_password == BCrypt::Engine.hash_secret(password, salt)
  end

  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end
end

app/controllers/adm_controller.rb
#encoding=UTF-8

class AdmController < ApplicationController
  before_filter :authenticate_user, :except=>[:login, :login_attempt, :logout]
  before_filter :verify_login_state, :only=>[:login, :login_attempt]

  def login
    @title = "II ENCATEC - Login"
  end

  def login_attempt
    @title = "II ENCATEC - Login"
    authorized_user = User.authenticate(params[:username],params[:password])

    if authorized_user
      session[:user_id] = authorized_user.id
      redirect_to posts_url
    else
      flash[:notice] = "Nome de usuário ou senha inválidos!"
      render "login"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :action => 'login'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
#encoding=UTF-8

class HomeController < ApplicationController
  def index
    @title = '2º Encontro Norte Capixaba de Tecnologia'
    @contact = Contact.new
  end

  def create_contact
    @contact = Contact.new(params[:contact])

    if @contact.valid?
      ContactsMailer.new_contact(@contact).deliver
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/inscreva_se_controller.rb
#encoding=UTF-8

class InscrevaSeController < ApplicationController
  def index
    @title = '2º Encontro Norte Capixaba de Tecnologia - Inscrição'
  end
end

app/controllers/posts_controller.rb
#encoding=UTF-8

class PostsController < ApplicationController
  before_filter :authenticate_user

  def index
    @title = 'II ENCATEC - Posts'
    @posts = Post.all
  end

  def show
    @title = 'II ENCATEC - Posts'
    @post = Post.find(params[:id])
  end

  def new
    @title = 'II ENCATEC - Posts'
    @post = Post.new
  end

  def edit
    @title = 'II ENCATEC - Posts'
    @post = Post.find(params[:id])
  end

  def create
    @title = 'II ENCATEC - Posts'
    @post = Post.new(params[:post])

    if @post.save
      redirect_to @post, :notice => 'Post was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @title = 'II ENCATEC - Posts'
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to @post, :notice =>  'Post was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_url
  end
end

app/helpers/adm_helper.rb
module AdmHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inscreva_se_helper.rb
module InscrevaSeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/adm/login.html.erb
<div class="container">
  <div class="row">
    <div class="span4"></div>
    <div class="span4">
      <div class="well" id="login-form">
        <h2>Log In</h2>
        <%= form_tag :action=>"login_attempt" do %>

            <%= label :username, "Usuário:" %>
            <%= text_field_tag :username, nil, :class=>"login-input" %>

            <%= label :senha, "Senha:" %>
            <%= password_field_tag :password, nil, :class=>"login-input" %>
            <br/>
            <%= submit_tag("Log In", :class=>"btn") %>

        <% end %>
      </div>

      <% if notice %>
        <div class="alert">
          <%= notice %>
        </div>
      <% end %>
    </div>
    <div class="span4"></div>
</div>

app/views/home/_contact_alert.html.haml
#alert
  %button{:type=>'button', :class=>'close', :data=>{:dismiss=>'alert'}} x
  %h3 Erro(s) ao enviar!
  %h4 Preencha corretamente os campos:
  %ul
    - @contact.errors.each do |error, message|
      %li= message

app/views/home/_contact_success.html.haml
#success
  %button{:type=>'button', :class=>'close', :data=>{:dismiss=>'alert'}} x
  %h3 Contato Enviado!
  %p{:class=>'justify'} Agradecemos o contato, caso seja necessário retornaremos em breve!

app/views/home/create_contact.js.erb
$.ajax({
  success: function() {
    <% if @contact.errors.any? %>
      $('#form-message').html("<%= escape_javascript(render :partial=>'contact_alert') %>");
    <% else %>
      $('#form-message').html("<%= escape_javascript(render :partial=>'contact_success') %>");
      $('#name').val('');
      $('#email').val('');
      $('#message').val('');
    <% end %>
  }
});

$('#submit').val('Enviar');
$('#submit').removeAttr('disabled');

app/views/inscreva_se/index.html.haml
%body#inscreva-se
  .row
    %nav.navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to image_tag('logo.jpg'), root_path, class: 'brand'

          .nav-collapse
            %ul.nav.pull-right
              %li= link_to 'Voltar a home', root_path

  .insc-block
    .container
      %h1 Atenção ao realizar a sua inscrição! Instruções:
      %h2= raw 'Para se inscrever nos minicursos, desafios e oficinas é <strong>obrigatória</strong> a inscrição no ENCATEC.'
      %h2 Só será aceita a inscrição em apenas uma oficina.
      %h2 Só será aceita a inscrição em apenas um minicurso.
      = link_to 'http://www.eventick.com.br/encatec?locale=pt', class: 'm-btn big', target: '_blank' do
        Inscreva-se
        %i.icon-ok

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= @title

    = stylesheet_link_tag 'application', :media => 'all'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400,300', :media => 'all'

    = javascript_include_tag 'application'

    = csrf_meta_tags
    %meta{property: 'og:image', content: "#{URI.join(root_url, image_path('logoencatec.png'))}"}

  -# Body
  = yield

  %footer
    .row-fluid.section
      .container
        %p
          Desenvolvido por
          %strong
            = link_to 'Adapti', 'http://www.adapti.info', target: '_blank'

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>